version: '3'
volumes:
  mongoVolume:
services:
  mongo:
    image: mongo:4
    container_name: mongo-dev
    volumes:
      - mongoVolume:/data/db
    ports:
      # map to host port to access using mongo cli.
      - "27017:27017" 
  server:
    image: node:12
    container_name: server-dev
    volumes:  
      - ./server/:/home/node/app
      # Mount symbolic link as a volume
      - ./client/src/contracts:/home/node/app/indexer/contracts
    working_dir: /home/node/app
    depends_on: 
      - mongo
      - ganache
    environment: 
      - MONGO_URL=mongodb://mongo/
      - PORT=3000
      - NODE_ENV=development
      - DOCKER=yes
    env_file: 
      - .env
    ports:
      - "3000:3000"
    command: bash -c "npm run devserver"
  client:
    image: node:12
    container_name: client-dev
    volumes:  
      - ./client/:/home/node/app
    working_dir: /home/node/app
    depends_on:
      - server
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    # Use npx concurrently to avoid create-react-app from clearing the console.
    command: bash -c "npx concurrently npm:start"
  ganache:
    image: trufflesuite/ganache-cli
    container_name: ganache-dev
    volumes: 
      - ./ganache:/home/ganache
    env_file: 
      - .env
    ports:
      - "8545:8545"
    command: --mnemonic "${MNEMONIC}" --db /home/ganache/ --networkId 5777 --quiet
  relay:
    image: node:12
    container_name: relay-dev
    working_dir: /home/node/app
    depends_on: 
      - ganache
    environment: 
      - NODE_ENV=development
    ports:
      - "8090:8090"
    command: bash -c "npm install @openzeppelin/gsn-helpers && npx oz-gsn run-relayer --quiet --ethereumNodeURL http://ganache:8545"