version: '3'
services:
  mongo:
    image: mongo:4
    container_name: mongo-dev
    volumes:
      - /data/db
    ports:
      - "27017:27017"
  server:
    image: node:12
    container_name: server-dev
    volumes:  
      - ./server/:/home/node/app
    working_dir: /home/node/app
    depends_on: 
      - mongo
    environment: 
      - MONGO_URL='mongodb://mongo/'
      - PORT=3000
    env_file: 
      - .env
    ports:
      - "3000:3000"
    command: bash -c "npm install -g npm && npm install && npm run devserver"
  client:
    image: node:12
    container_name: client-dev
    volumes:  
      - ./client/:/home/node/app
    working_dir: /home/node/app
    depends_on:
      - server
    environment:
      - PORT=3001
    expose:
      - "3001"
    ports:
      - "3001:3001"
    command: bash -c "npm install -g npm && npm install && npm start"
  ganache:
    image: trufflesuite/ganache-cli
    container_name: ganache-dev
    volumes: 
      - ./ganache:/home/ganache
    expose: 
      - "8545"
    env_file: 
      - .env
    ports:
      - "8545:8545"
    command: ganache-cli --mnemonic "${MNEMONIC}" --db /home/ganache/  --networkId 5777 --quiet