version: '3'
services:
  mongo:
    image: mongo:4.2.3-bionic
    container_name: peer-review-mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: peer-review-server
    working_dir: /home/node/app
    depends_on: 
      - mongo
    environment: 
      - MONGO_URL='mongodb://mongo/'
      - PORT=3000
    env_file: .env
    ports:
      - "3000:3000"
    restart: always
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: peer-review-client
    working_dir: /home/node/app
    depends_on:
      - server
    expose:
      - "80"
    ports:
      - "80:80"
    restart: always