version: '3'
services:
  mongo:
    image: mongo:4.2.3-bionic
    container_name: peer-review-mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"
    environment: 
      - NODE_ENV=production
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: peer-review-server
    working_dir: /home/node/app
    volumes:
      # indexer needs to access contract builds.
      - ./client/src/contracts/:/home/node/app/indexer/contracts
    depends_on: 
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo/
      - PORT=3000
      - DOCKER=yes
    env_file: 
      - .env
    ports:
      - "3000:3000"
    restart: always
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: peer-review-client
    working_dir: /home/node/app
    depends_on:
      - server
    env_file: 
      - .env
    expose:
      - "80"
    ports:
      - "80:80"
    restart: always